###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: decoupling-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=q1w2e3
        - MYSQL_DATABASE=digimon_chart
        - MYSQL_USER=edison
        - MYSQL_PASSWORD=q1w2e3
      ports:
        - "8901:3306"

    postgres:
      image: postgres:9.6-alpine
      container_name: decoupling-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=q1w2e3
        - POSTGRES_DB=digimon_chart

    webserver:
      image: nginx:alpine
      container_name: decoupling-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8899:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: decoupling-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

